DROP DATABASE IF EXISTS GAMEPLATAFORM;

CREATE DATABASE GAMEPLATAFORM;

USE GAMEPLATAFORM;

/* DROP TABLE IF EXISTS PRODUCTORA;
DROP TABLE IF EXISTS SAGA;
DROP TABLE IF EXISTS JUEGO;
DROP TABLE IF EXISTS JUEGOSGENERO;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS BIBLIOTECA;
DROP TABLE IF EXISTS DESEADOS;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS IDIOMASJUEGO;
DROP TABLE IF EXISTS IDIOMAS;
DROP TABLE IF EXISTS RESENA;
DROP TABLE IF EXISTS JUEGOPLATAFORMA;
DROP TABLE IF EXISTS PLATAFORMA;
DROP TABLE IF EXISTS AVATAR;
DROP TABLE IF EXISTS PARTIDAS; */


CREATE TABLE PRODUCTORA (
    IDPRODUCTORA INT,
    NOMBRE VARCHAR(50)
);


CREATE TABLE SAGA (
    IDSAGA INT, 
    IDPRODUCTORA INT,
    NOMBRE VARCHAR(255),
    FECHA DATE
);

CREATE TABLE JUEGO(
    IDJUEGO INT,
    IDSAGA INT, 
    TITULO VARCHAR(255),
    PRECIO FLOAT,
    FECHALANZAMIENTO DATE,
    DESCRIPCION VARCHAR(255),
    URLIMAGEN VARCHAR(255),
    CLASIFICACION VARCHAR(1),
    PUNTUACION FLOAT
);


CREATE TABLE JUEGOSGENERO (
    IDJUEGO INT, 
    IDGENERO VARCHAR(255)
);

CREATE TABLE GENERO (
    IDGENERO INT, 
    NOMBREGENERO VARCHAR(255)
);


CREATE TABLE BIBLIOTECA (
    IDJUEGO INT, 
    IDUSUARIO INT, 
    MODOADQUISICION INT, 
    FECHAADQUISICION DATE, 
    DESCUENTO FLOAT, 
    PRECIOCOMPRA FLOAT
);

CREATE TABLE DESEADOS (
    IDJUEGO INT,
    IDUSUARIO INT, 
    FECHAAGREGADO DATE
);


CREATE TABLE USUARIO (
    IDUSUARIO INT, 
    NOMBRE VARCHAR(255),
    SALDOCARTERA FLOAT,
    CORREO VARCHAR(255),
    NUMEROCELULAR VARCHAR(255)
);



CREATE TABLE IDIOMASJUEGO (
    IDJUEGO INT, 
    IDIDIOMA INT    
);



CREATE TABLE IDIOMAS (
    IDIDIOMA INT, 
    IDIOMA VARCHAR(30)
);


CREATE TABLE RESENA (
    IDJUEGO INT, 
    IDUSUARIO INT, 
    DESCRIPTION VARCHAR(255)
);



CREATE TABLE JUEGOPLATAFORMA (
    IDJUEGO INT, 
    IDPLATAFORMA INT
);


CREATE TABLE PLATAFORMA (
    IDPLATAFORMA INT, 
    NOMBRE VARCHAR(50)
);


CREATE TABLE AVATAR (
    IDJUEGO INT, 
    IDUSUARIO INT, 
    NOMBRE VARCHAR(50)
);


CREATE TABLE PARTIDAS (
    IDJUEGO INT, 
    IDUSUARIO INT, 
    FECHAINICIO DATETIME, 
    FECHAFIN DATETIME, 
    ONLINE_ BOOLEAN    
);
