USE GAMEPLATAFORM;


TRUNCATE TABLE PARTIDAS;
TRUNCATE TABLE AVATAR;
TRUNCATE TABLE BIBLIOTECA;
TRUNCATE TABLE DESEADOS;
TRUNCATE TABLE USUARIO;
TRUNCATE TABLE JUEGO;
TRUNCATE TABLE SAGA;
TRUNCATE TABLE PRODUCTORA;


LOAD DATA INFILE 'Data/Productora.csv'
INTO TABLE PRODUCTORA
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Data/Saga.csv'
INTO TABLE SAGA
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


LOAD DATA INFILE 'Data/Juego.csv'
INTO TABLE JUEGO
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


LOAD DATA INFILE 'Data/Biblioteca.csv'
INTO TABLE BIBLIOTECA
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


LOAD DATA INFILE 'Data/Deseado.csv'
INTO TABLE DESEADOS
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


LOAD DATA INFILE 'Data/Usuario.csv'
INTO TABLE USUARIO
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Data/Avatar.csv'
INTO TABLE AVATAR
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Data/Partida.csv'
INTO TABLE PARTIDAS
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
