
SELECT P.NOMBRE AS PRODUCTORANOMBRE,
    S.NOMBRE AS SAGANOMBRE,
    J.TITULO, 
    A.IDUSUARIO AS AVATARUSUARIOID, A.NOMBRE AS AVATARNOMBRE,
    PA.FECHAINICIO, PA.FECHAFIN
FROM PRODUCTORA P
    JOIN SAGA S ON P.IDPRODUCTORA = S.IDPRODUCTORA
    JOIN JUEGO J ON S.IDSAGA = J.IDSAGA
    JOIN AVATAR A ON J.IDJUEGO = A.IDJUEGO
    JOIN PARTIDAS PA ON J.IDJUEGO = PA.IDJUEGO AND A.IDUSUARIO = PA.IDUSUARIO;



SELECT COUNT(*) AS CONTEO
FROM PRODUCTORA P
    JOIN SAGA S ON P.IDPRODUCTORA = S.IDPRODUCTORA
    JOIN JUEGO J ON S.IDSAGA = J.IDSAGA
    JOIN AVATAR A ON J.IDJUEGO = A.IDJUEGO
    JOIN PARTIDAS PA ON J.IDJUEGO = PA.IDJUEGO AND A.IDUSUARIO = PA.IDUSUARIO;
