DROP DATABASE IF EXISTS GamePlatform_OLAP;
CREATE DATABASE GamePlatform_OLAP;
USE GamePlatform_OLAP;

CREATE TABLE JUEGO(
    IDJUEGO INT,
    IDSAGA INT, 
    TITULO VARCHAR(255),
    PRECIO FLOAT,
    FECHALANZAMIENTO DATE,
    DESCRIPCION VARCHAR(255),
    URLIMAGEN VARCHAR(255),
    CLASIFICACION VARCHAR(1),
    PUNTUACION FLOAT
);

CREATE TABLE SAGA (
    IDSAGA INT, 
    IDPRODUCTORA INT,
    NOMBRE VARCHAR(255),
    FECHA DATE
);

CREATE TABLE USUARIO (
    IDUSUARIO INT, 
    NOMBRE VARCHAR(255),
    SALDOCARTERA FLOAT
);

CREATE TABLE PRODUCTORA (
    IDPRODUCTORA INT,
    NOMBRE VARCHAR(50)
);

CREATE TABLE FECHA (
    IDFECHA INT PRIMARY KEY AUTO_INCREMENT,
    ANIO INT,
    MES INT,
    DIA INT
);

CREATE TABLE HECHOS (
    IDJUEGO INT,
    IDSAGA INT,
    IDPRODUCTORA INT,
    IDUSUARIO INT,
    IDFECHA INT,
    AVG_DURACION FLOAT,
    SUM_DURACION INT,
    MAX_DURACION INT,
    MIN_DURACION INT,
    NUM_PARTIDAS INT
);

--  INSERT

LOAD DATA INFILE 'Data/Juego.csv'
INTO TABLE JUEGO
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Data/Saga.csv'
INTO TABLE SAGA
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

INSERT INTO GamePlatform_OLAP.USUARIO 
    (
        IDUSUARIO, 
        NOMBRE, 
        SALDOCARTERA
    )
    SELECT
        IDUSUARIO,
        NOMBRE,
        SALDOCARTERA
    FROM GAMEPLATAFORM.USUARIO;

LOAD DATA INFILE 'Data/Productora.csv'
INTO TABLE PRODUCTORA
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

INSERT INTO GamePlatform_OLAP.FECHA
    (
        IDFECHA,
        ANIO,
        MES,
        DIA
    )
    SELECT
        DISTINCT
        DENSE_RANK() OVER (ORDER BY DATE(FECHAFIN)) AS IDFECHA,
        YEAR(FECHAFIN) AS ANIO,
        MONTH(FECHAFIN) AS MES,
        DAY(FECHAFIN) AS DIA
    FROM GAMEPLATAFORM.PARTIDAS
    ORDER BY ANIO, MES, DIA;

INSERT INTO GamePlatform_OLAP.HECHOS
    (
        IDJUEGO,
        IDSAGA,
        IDPRODUCTORA,
        IDUSUARIO,
        IDFECHA,
        AVG_DURACION,
        SUM_DURACION,
        MAX_DURACION,
        MIN_DURACION,
        NUM_PARTIDAS
    )
    SELECT
        R.IDJUEGO,
        R.IDSAGA,
        R.IDPRODUCTORA,
        R.IDUSUARIO,
        R.ID_FECHA,
        AVG(R.DURACION) AS AVG_DURACION,
        SUM(R.DURACION) AS SUM_DURACION,
        MAX(R.DURACION) AS MAX_DURACION,
        MIN(R.DURACION) AS MIN_DURACION,
        COUNT(R.DURACION) AS NUM_PARTIDAS
    FROM (
        SELECT
            J.IDJUEGO,
            S.IDSAGA,
            P.IDPRODUCTORA,
            Par.IDUSUARIO,
            DENSE_RANK() OVER (ORDER BY DATE(Par.FECHAFIN)) AS ID_FECHA,
            TIMESTAMPDIFF(SECOND, Par.FECHAINICIO, Par.FECHAFIN) AS DURACION
        FROM
            GAMEPLATAFORM.PRODUCTORA P
        LEFT JOIN GAMEPLATAFORM.SAGA S ON P.IDPRODUCTORA = S.IDPRODUCTORA
        LEFT JOIN GAMEPLATAFORM.JUEGO J ON S.IDSAGA = J.IDSAGA
        LEFT JOIN GAMEPLATAFORM.PARTIDAS Par ON Par.IDJUEGO = J.IDJUEGO
    ) R
    GROUP BY
        R.IDJUEGO,
        R.IDSAGA,
        R.IDPRODUCTORA,
        R.IDUSUARIO,
        R.ID_FECHA
    ORDER BY
        R.ID_FECHA;





SELECT * 
FROM GamePlatform_OLAP.HECHOS
INTO OUTFILE 'Data/SFHechos.csv'
fields terminated BY ','
lines terminated BY '\n';

SELECT * 
FROM GamePlatform_OLAP.FECHA
INTO OUTFILE 'Data/SFFecha.csv'
fields terminated BY ','
lines terminated BY '\n';

SELECT * 
FROM GamePlatform_OLAP.USUARIO
INTO OUTFILE 'Data/SFUsuario.csv'
fields terminated BY ','
lines terminated BY '\n';
